/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.md in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

export interface PlanData {
    status: string;
    created: string;
    mode: string;
    sections: PlanSection[];
    parseError?: PlanParseError;
    /**
     * HTML/CSS preview pages generated by the planner agent into
     * `.azure/.preview-temp/`. Populated by the controller (NOT the markdown
     * parser) and refreshed via a file-system watcher. Undefined when no
     * preview folder exists for the workspace.
     */
    previewPages?: PreviewPage[];
}

export interface PreviewPage {
    slug: string;
    title: string;
    route: string;
    /**
     * Fully self-contained HTML (with `theme.css` inlined into a `<style>`
     * block) ready to drop into an `<iframe srcDoc=…>`. Undefined while the
     * page is still being generated by a sub-agent.
     */
    html?: string;
    status: 'pending' | 'ready';
}

/**
 * Top-level status of the preview set written to `manifest.json`.
 * - `"generating"` — initial generation or revision in progress.
 * - `"ready"` — all preview work is complete.
 */
export type PreviewStatus = 'generating' | 'ready';

export interface PlanParseError {
    message: string;
    fileLabel?: string;
}

export interface PlanSection {
    number: number;
    title: string;
    content: PlanContent[];
}

export interface TreeNode {
    name: string;
    comment?: string;
    isFolder: boolean;
    children: TreeNode[];
}

export interface PaletteEntry {
    token: string;
    hex: string;
    usage: string;
}

export interface PageEntry {
    page: string;
    route: string;
    purpose: string;
}

export type PlanContent =
    | { type: 'keyValue'; key: string; value: string }
    | { type: 'table'; headers: string[]; rows: string[][] }
    | { type: 'blockquote'; text: string }
    | { type: 'paragraph'; text: string }
    | { type: 'tree'; root: string; nodes: TreeNode[] }
    | { type: 'colorPalette'; entries: PaletteEntry[] }
    | { type: 'pages'; entries: PageEntry[] };

export function parseScaffoldPlanMarkdown(markdown: string): PlanData {
    const lines = markdown.replace(/\r\n/g, '\n').split('\n');

    const status = extractMetadata(lines, 'Status') ?? 'Unknown';
    const created = extractMetadata(lines, 'Created') ?? 'Unknown';
    const mode = extractMetadata(lines, 'Mode') ?? 'Unknown';

    const sections = extractSections(lines);
    specializeDesignSystemSection(sections);

    return { status, created, mode, sections };
}

function extractMetadata(lines: string[], key: string): string | undefined {
    for (const line of lines) {
        const match = line.match(new RegExp(`^\\*\\*${key}\\*\\*\\s*:\\s*(.+)$`));
        if (match) {
            return match[1].trim();
        }
    }
    return undefined;
}

function extractSections(lines: string[]): PlanSection[] {
    const sections: PlanSection[] = [];
    let currentSection: PlanSection | undefined;
    let i = 0;

    while (i < lines.length) {
        const line = lines[i];

        // Match section headers like "## 1. Project Overview"
        const sectionMatch = line.match(/^##\s+(\d+)\.\s+(.+)$/);
        if (sectionMatch) {
            currentSection = {
                number: parseInt(sectionMatch[1], 10),
                title: sectionMatch[2].trim(),
                content: [],
            };
            sections.push(currentSection);
            i++;
            continue;
        }

        if (!currentSection) {
            i++;
            continue;
        }

        // Skip empty lines and horizontal rules
        if (line.trim() === '' || line.trim() === '---') {
            i++;
            continue;
        }

        // Handle fenced code blocks. If the fence wraps a tree, parse the inside
        // as a tree; otherwise skip the fence content.
        if (line.trim() === '```' || line.trim().startsWith('```')) {
            const next = lines[i + 1]?.trim() ?? '';
            const looksLikeTree =
                next === '.' ||
                /^[a-zA-Z0-9._-]+\/$/.test(next) ||
                next.startsWith('├') || next.startsWith('└') || next.startsWith('│');
            if (looksLikeTree) {
                const tree = parseTree(lines, i + 1);
                if (tree) {
                    currentSection.content.push(tree.content);
                    i = tree.endIndex;
                    // Skip the closing fence if present
                    if (i < lines.length && lines[i].trim() === '```') {
                        i++;
                    }
                    continue;
                }
            }
            // Skip to closing fence (or EOF) so fence contents don't pollute the section
            i++;
            while (i < lines.length && lines[i].trim() !== '```') {
                i++;
            }
            if (i < lines.length) {
                i++;
            }
            continue;
        }

        // Parse tree structures (lines starting with tree connectors or a root folder)
        if (line.trim() === '.' || line.trim().match(/^[a-zA-Z0-9._-]+\/$/) || line.trim().startsWith('├') || line.trim().startsWith('└') || line.trim().startsWith('│')) {
            const tree = parseTree(lines, i);
            if (tree) {
                currentSection.content.push(tree.content);
                i = tree.endIndex;
                continue;
            }
        }

        // Parse tables
        if (line.trim().startsWith('|')) {
            const table = parseTable(lines, i);
            if (table) {
                currentSection.content.push(table.content);
                i = table.endIndex;
                continue;
            }
        }

        // Parse blockquotes
        if (line.trim().startsWith('>')) {
            const text = line.trim().replace(/^>\s*/, '');
            currentSection.content.push({ type: 'blockquote', text });
            i++;
            continue;
        }

        // Parse bold key-value pairs like "**Goal**: ..."
        const kvMatch = line.match(/^\*\*(.+?)\*\*\s*:\s*(.+)$/);
        if (kvMatch) {
            currentSection.content.push({
                type: 'keyValue',
                key: kvMatch[1].trim(),
                value: kvMatch[2].trim(),
            });
            i++;
            continue;
        }

        // Fallback: paragraph
        if (line.trim().length > 0) {
            currentSection.content.push({ type: 'paragraph', text: line.trim() });
        }

        i++;
    }

    return sections;
}

function parseTable(lines: string[], startIndex: number): { content: PlanContent; endIndex: number } | undefined {
    const headerLine = lines[startIndex];
    if (!headerLine?.trim().startsWith('|')) {
        return undefined;
    }

    const headers = parseTableRow(headerLine);
    if (headers.length === 0) {
        return undefined;
    }

    // Skip the separator line (e.g., |---|---|)
    let i = startIndex + 1;
    if (i < lines.length && lines[i].trim().match(/^\|[\s\-|]+\|$/)) {
        i++;
    }

    const rows: string[][] = [];
    while (i < lines.length && lines[i].trim().startsWith('|')) {
        rows.push(parseTableRow(lines[i]));
        i++;
    }

    return {
        content: { type: 'table', headers, rows },
        endIndex: i,
    };
}

function parseTableRow(line: string): string[] {
    return line
        .split('|')
        .slice(1, -1) // Remove leading/trailing empty strings from split
        .map((cell) => cell.trim().replace(/\*\*/g, '')); // Strip bold markers
}

function parseTree(lines: string[], startIndex: number): { content: PlanContent; endIndex: number } | undefined {
    let i = startIndex;
    const firstLine = lines[i].trim();

    // First line should be the root folder (e.g. "project-root/") or '.' for current dir
    const rootMatch = firstLine.match(/^(\.|[a-zA-Z0-9._-]+\/)\s*$/);
    if (!rootMatch) {
        return undefined;
    }

    const root = rootMatch[1];
    i++;

    // Collect all tree lines
    const treeLines: string[] = [];
    while (i < lines.length) {
        const line = lines[i];
        if (line.trim() === '```') {
            break;
        }
        if (line.match(/[├└│]/) || (line.startsWith('    ') && treeLines.length > 0)) {
            treeLines.push(line);
            i++;
        } else if (line.trim() === '') {
            i++;
            break;
        } else {
            break;
        }
    }

    const nodes = buildTreeNodes(treeLines, 0);
    return { content: { type: 'tree', root, nodes }, endIndex: i };
}

function buildTreeNodes(lines: string[], depth: number): TreeNode[] {
    const nodes: TreeNode[] = [];
    let i = 0;

    while (i < lines.length) {
        const line = lines[i];

        // Calculate this line's depth by counting indentation units
        const lineDepth = getTreeDepth(line);

        if (lineDepth < depth) {
            break;
        }

        if (lineDepth > depth) {
            i++;
            continue;
        }

        // Extract name and optional comment
        const cleaned = line.replace(/[│├└─\s]/g, '').trim();
        if (!cleaned) {
            i++;
            continue;
        }

        // More precise extraction: find the connector then get the rest
        const connectorMatch = line.match(/[├└]──\s+(.+)/);
        if (!connectorMatch) {
            i++;
            continue;
        }

        let nameAndComment = connectorMatch[1].trim();
        let comment: string | undefined;

        // Extract trailing comment. Supports both "← description" and "# description".
        const commentMatch = nameAndComment.match(/^(.+?)\s+(?:←|#)\s+(.+)$/);
        if (commentMatch) {
            nameAndComment = commentMatch[1].trim();
            comment = commentMatch[2].trim();
        }

        const isFolder = nameAndComment.endsWith('/');
        const name = nameAndComment;

        // Collect children (lines at deeper depth)
        const children: string[] = [];
        let j = i + 1;
        while (j < lines.length && getTreeDepth(lines[j]) > depth) {
            children.push(lines[j]);
            j++;
        }

        const node: TreeNode = {
            name,
            comment,
            isFolder,
            children: children.length > 0 ? buildTreeNodes(children, depth + 1) : [],
        };

        nodes.push(node);
        i = j;
    }

    return nodes;
}

function getTreeDepth(line: string): number {
    let depth = 0;
    let pos = 0;

    while (pos < line.length) {
        // Check for "│   " (pipe + 3 spaces) or "    " (4 spaces)
        const chunk = line.substring(pos, pos + 4);
        if (chunk === '│   ' || chunk === '    ') {
            depth++;
            pos += 4;
        } else {
            break;
        }
    }

    return depth;
}

/**
 * After generic section parsing, look at Section 5 ("Design System & UI") and
 * upgrade its tables to the typed `colorPalette` / `pages` content variants the
 * UI preview card reads from. Tables that don't match either shape are left
 * alone as plain `table` content.
 */
function specializeDesignSystemSection(sections: PlanSection[]): void {
    const designSection = sections.find(s => s.title.toLowerCase().includes('design system'));
    if (!designSection) {
        return;
    }

    designSection.content = designSection.content.map((item) => {
        if (item.type !== 'table') {
            return item;
        }
        const palette = tryParseColorPalette(item.headers, item.rows);
        if (palette) {
            return palette;
        }
        const pages = tryParsePages(item.headers, item.rows);
        if (pages) {
            return pages;
        }
        return item;
    });
}

const HEX_RE = /^#?[0-9a-f]{3,8}$/i;

function stripHexCell(raw: string): string {
    // Tolerate placeholder wrappers the agent docs use, e.g. `{#0078D4}` or `*#0078D4*`.
    return raw.trim().replace(/^[{[(*_`]+|[}\])*_`]+$/g, '').trim();
}

function tryParseColorPalette(headers: string[], rows: string[][]): PlanContent | undefined {
    if (rows.length === 0) {
        return undefined;
    }
    const headerLower = headers.map(h => h.toLowerCase().trim());
    const tokenIdx = headerLower.findIndex(h => h === 'token');
    const colorIdx = headerLower.findIndex(h => h === 'color' || h === 'hex' || h === 'value');
    const usageIdx = headerLower.findIndex(h => h === 'usage' || h === 'role' || h === 'use');

    let hexColumn = colorIdx;
    if (hexColumn < 0) {
        // Fall back to whichever column looks most hex-ish across rows.
        for (let c = 0; c < headers.length; c++) {
            const matches = rows.filter(r => HEX_RE.test(stripHexCell(r[c] ?? ''))).length;
            if (matches >= Math.max(1, Math.floor(rows.length / 2))) {
                hexColumn = c;
                break;
            }
        }
    }

    if (hexColumn < 0) {
        return undefined;
    }

    const tokenColumn = tokenIdx >= 0 ? tokenIdx : 0;
    const usageColumn = usageIdx >= 0 ? usageIdx : (hexColumn + 1 < headers.length ? hexColumn + 1 : -1);

    const entries: PaletteEntry[] = [];
    for (const row of rows) {
        const rawHex = stripHexCell(row[hexColumn] ?? '');
        if (!HEX_RE.test(rawHex)) {
            continue;
        }
        const token = (row[tokenColumn] ?? '').trim();
        if (!token || tokenColumn === hexColumn) {
            continue;
        }
        entries.push({
            token,
            hex: rawHex.startsWith('#') ? rawHex : `#${rawHex}`,
            usage: usageColumn >= 0 ? (row[usageColumn] ?? '').trim() : '',
        });
    }

    if (entries.length === 0) {
        return undefined;
    }
    return { type: 'colorPalette', entries };
}

function tryParsePages(headers: string[], rows: string[][]): PlanContent | undefined {
    if (rows.length === 0) {
        return undefined;
    }
    const headerLower = headers.map(h => h.toLowerCase().trim());
    const layoutIdx = headerLower.findIndex(h => h === 'layout' || h === 'regions');
    if (layoutIdx < 0) {
        return undefined;
    }
    const pageIdx = headerLower.findIndex(h => h === 'page' || h === 'name' || h === 'screen');
    const routeIdx = headerLower.findIndex(h => h === 'route' || h === 'path' || h === 'url');
    const purposeIdx = headerLower.findIndex(h => h === 'purpose' || h === 'description' || h === 'desc');

    const pageCol = pageIdx >= 0 ? pageIdx : 0;

    const entries: PageEntry[] = [];
    for (const row of rows) {
        const page = (row[pageCol] ?? '').trim();
        if (!page) {
            continue;
        }
        const layoutCell = (row[layoutIdx] ?? '').trim();
        if (!layoutCell) {
            continue;
        }
        entries.push({
            page,
            route: routeIdx >= 0 ? (row[routeIdx] ?? '').trim() : '',
            purpose: purposeIdx >= 0 ? (row[purposeIdx] ?? '').trim() : '',
        });
    }

    if (entries.length === 0) {
        return undefined;
    }
    return { type: 'pages', entries };
}


