variables:
  WEB_BUILDS_STG_ACCT: vscodedotdev
  WEB_BUILDS_CONTAINER: web-builds
  ${{ if eq(variables['Build.Reason'], 'Schedule') }}:
    ENABLE_LONG_RUNNING_TESTS: true
    ENABLE_COMPLIANCE: true

# Trigger the build whenever `main` or `rel/*` is updated
trigger:
  - main
  - rel/*

pr: none # Disable PR trigger

# Scheduled nightly build
schedules:
  - cron: "30 9 * * *"
    displayName: Nightly at 2:30 PT
    always: true # Run even when there are no code changes
    branches:
      include:
        - main

# Grab the base templates from https://github.com/microsoft/vscode-azuretools/tree/main/azure-pipelines
resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-azuretools
      ref: main
      endpoint: GitHub

# Use those templates
extends:
  template: azure-pipelines/jobs.yml@templates
