name: 'API: Publish to npm'
# Publishes the api package to npm

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  api-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - uses: JS-DevTools/npm-publish@v1
        name: Publish package
        with:
          package: ./api/package.json
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
