name: 'API: Publish to npm'
# Publishes the api package to npm

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  api-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Setup node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - uses: JS-DevTools/npm-publish@0f451a94170d1699fd50710966d48fb26194d939 # v1.4.3
        name: Publish package
        with:
          package: ./api/package.json
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
